name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        # The root LaTeX file to be compiled
        root_file: main.tex
        # The working directory for the LaTeX engine
        working_directory: # optional
        # The LaTeX engine to be invoked
        compiler: # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # [Deprecated] Install extra packages by tlmgr
        extra_packages: # optional
        # Install extra packages by apk
        extra_system_packages: # optional
